### ISSUE TITLE
license

### ISSUE THREAD

**Issue by slivingston** [MistyCommunity/Blockly#1]
can you add a license file in order to explicitly declare this as open source?

e.g., this can be like [LICENSE](https://github.com/MistyCommunity/Wrapper-Python/blob/16c9197105a7e16b56bac36261d20e7be4ecabcc/LICENSE) in <https://github.com/MistyCommunity/Wrapper-Python/>

**Comment by brad-allen** [comment]
Added.  Let us know if that works!

**Comment by slivingston** [comment]
Yes, thanks!
