### ISSUE TITLE
commit JS code

### ISSUE THREAD

**Issue by slivingston** [MistyCommunity/Blockly#2]
can you commit the JavaScript source code for Blockly?

in particular, the files that are included [on lines 406-417](https://github.com/MistyCommunity/Blockly/blob/302d1e7b6c248896f2cafdeb536833fba03d236b/index.html#L406-L417) appear to be critical.

my motivation to ask: if you want someone to be able to hack on Blockly for Misty robots, then they need all of the source code for building the website that is not already hosted in a different repository.

for example, jquery-ui.min.js is included in index.html but should not be committed to this repo because it is already available elsewhere (<https://jqueryui.com/download/> or <https://github.com/jquery/jquery-ui>). in contrast, misty_blocks.js should be included in this repo.

**Comment by brad-allen** [comment]
Committed for you!  Just a note, we generally include all the files we may need due to the fact that not every place we use our tools has an internet connection.

**Comment by slivingston** [comment]
Thanks! I understand the motivation you give (and other motivations) for "vendoring". Your call, of course.
